# currently appveyor is disabled in favor of azure pipelines.
# to re-enable it, we need to activate the corresponding github webhook.
version: 1.0.{build}
image: Visual Studio 2017
#init:
#  tzutil /s "W. Europe Standard Time"
before_build:
  cmd: nuget restore ./src/FatturaElettronica.sln
build:
  project: ./src/FatturaElettronica.sln
  verbosity: minimal
