name: Build

on:
   push:
    branches:
      - net_35

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'          
    - name: Setup .NET Core 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}} 
    - name: Install dependencies
      run: dotnet restore ./src/
    - name: Build
      run: dotnet build ./src/ --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/ --verbosity normal  --no-restore
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Test on ${{ matrix.os }}
        reporter: dotnet-trx
        path: ./TestResults/*/*.trx
